[platformio]
default_envs = crossing-controller

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.0
build_flags =
  -D OTA_REPOSITORY_OWNER=\"GeorgeHinch\"
  -D OTA_REPOSITORY_NAME=\"esp32-github-ota\"

[env:crossing-controller]
board = esp32-c3-devkitm-1
build_flags =
  ${env.build_flags}
  -D DEVICE_TYPE=\"crossing-controller\"
  -D HARDWARE_TARGET=\"esp32-c3\"
  -D HARDWARE_REVISION=1
  -D FIRMWARE_VERSION=\"0.1.0\"
