[CmdletBinding()]
param(
  [ValidatePattern('^[A-Za-z0-9_-]+$')]
  [string]$DeviceType = 'audio_sensor',
  [Parameter(Mandatory)]
  [string]$Version,
  [string]$Fqbn = 'esp32:esp32:esp32c3:CDCOnBoot=cdc,PartitionScheme=min_spiffs',
  [string]$Remote = 'origin',
  [switch]$Push
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

if ($Version.StartsWith('v')) { $Version = $Version.Substring(1) }
if ($Version -notmatch '^\d+\.\d+\.\d+$') {
  throw "Version must use major.minor.patch format, for example 0.1.6. Received: $Version"
}

$gitRoot = (& git -C $repoRoot rev-parse --show-toplevel 2>$null)
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($gitRoot)) {
  throw 'The workspace is not connected to a Git repository. Initialize it and add a GitHub remote before publishing.'
}
$gitRoot = (Resolve-Path $gitRoot.Trim()).Path
if ($gitRoot -ne $repoRoot) {
  throw "The Git repository root is $gitRoot, but this firmware workspace is $repoRoot."
}

& git -C $repoRoot diff --cached --quiet
if ($LASTEXITCODE -ne 0) {
  throw 'The Git index already contains staged changes. Commit or unstage them before publishing.'
}

$tag = "$DeviceType/v$Version"
$existingTag = (& git -C $repoRoot tag --list $tag)
if (-not [string]::IsNullOrWhiteSpace($existingTag)) {
  throw "Git tag already exists: $tag"
}

$releaseRoot = Join-Path $repoRoot "firmware\$DeviceType\v$Version"
if (-not (Test-Path -LiteralPath $releaseRoot)) {
  throw "Release folder not found: $releaseRoot. Create it with New-FirmwareRelease.ps1 first."
}

$expectedStem = "${DeviceType}_$($Version -replace '\.', '_')"
$sketchFiles = @(Get-ChildItem -LiteralPath $releaseRoot -File -Filter '*.ino')
$mainSketches = @($sketchFiles | Where-Object { $_.BaseName -eq $expectedStem })
if ($mainSketches.Count -ne 1) {
  throw "Expected one main sketch named $expectedStem.ino; found $($mainSketches.Count)."
}
$sketch = $mainSketches[0]
$artifactStem = $sketch.BaseName

# Arduino requires the temporary sketch folder and its main .ino file to have
# the same name. The release folder remains flat; this staging copy is temporary.
$tempRoot = Join-Path ([IO.Path]::GetTempPath()) "device-firmware-build\$DeviceType\v$Version"
if (Test-Path -LiteralPath $tempRoot) { Remove-Item -LiteralPath $tempRoot -Recurse -Force }
$tempSketchDir = Join-Path $tempRoot $artifactStem
$tempBuildPath = Join-Path $tempRoot 'build'
New-Item -ItemType Directory -Path $tempSketchDir -Force | Out-Null
Get-ChildItem -LiteralPath $releaseRoot -File -Filter '*.ino' | Copy-Item -Destination $tempSketchDir
Get-ChildItem -LiteralPath $releaseRoot -File -Filter '*.h' | Copy-Item -Destination $tempSketchDir

$arduinoCli = (Get-Command arduino-cli -ErrorAction SilentlyContinue).Source
if ([string]::IsNullOrWhiteSpace($arduinoCli)) {
  $arduinoCli = 'C:\Program Files\Arduino IDE\resources\app\lib\backend\resources\arduino-cli.exe'
}
if (-not (Test-Path -LiteralPath $arduinoCli)) {
  throw 'arduino-cli was not found. Install Arduino CLI or Arduino IDE first.'
}

Write-Host "Compiling cleanly from $tempSketchDir"
& $arduinoCli compile $tempSketchDir --fqbn $Fqbn --build-path $tempBuildPath --clean --warnings default
if ($LASTEXITCODE -ne 0) { throw 'Firmware compilation failed.' }

$compiledName = "$($sketch.Name).bin"
$compiled = @(Get-ChildItem -LiteralPath $tempBuildPath -Recurse -File -Filter $compiledName)
if ($compiled.Count -ne 1) {
  throw "Expected one compiled application binary in $tempBuildPath; found $($compiled.Count)."
}

$releaseBinary = Join-Path $releaseRoot "$artifactStem.bin"
Copy-Item -LiteralPath $compiled[0].FullName -Destination $releaseBinary -Force
$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $releaseBinary).Hash.ToLowerInvariant()
$size = (Get-Item -LiteralPath $releaseBinary).Length

$buildInfo = @"
# $DeviceType v$Version

- Status: Clean build completed
- Sketch: ``$($sketch.Name)``
- Binary: ``$artifactStem.bin``
- FQBN: ``$Fqbn``
- Binary size: $size bytes
- Binary SHA-256: ``$hash``

This release was generated by ``tools\Publish-Firmware.ps1``.
"@
Set-Content -LiteralPath (Join-Path $releaseRoot 'BUILD_INFO.md') -Value $buildInfo -Encoding utf8

& git -C $repoRoot diff --check
if ($LASTEXITCODE -ne 0) { throw 'Git whitespace validation failed.' }

$relativeRelease = $releaseRoot.Substring($repoRoot.Length).TrimStart('\').Replace('\', '/')
& git -C $repoRoot add -- $relativeRelease
if ($LASTEXITCODE -ne 0) { throw 'Could not stage the firmware release.' }
& git -C $repoRoot commit -m "firmware($DeviceType): publish v$Version"
if ($LASTEXITCODE -ne 0) { throw 'Git commit failed.' }
& git -C $repoRoot tag -a $tag -m "$DeviceType v$Version"
if ($LASTEXITCODE -ne 0) { throw 'Git tag creation failed.' }

if ($Push) {
  & git -C $repoRoot push $Remote HEAD
  if ($LASTEXITCODE -ne 0) { throw "Could not push the current branch to $Remote." }
  & git -C $repoRoot push $Remote $tag
  if ($LASTEXITCODE -ne 0) { throw "Could not push tag $tag to $Remote." }
  Write-Host "Pushed branch and tag $tag to $Remote"
} else {
  Write-Host "Created commit and tag $tag locally. Re-run with -Push to publish to $Remote."
}

Write-Host "Binary: $releaseBinary"
Write-Host "SHA-256: $hash"
