#ifndef DISTANCE_SENSOR_H
#define DISTANCE_SENSOR_H

#include <Adafruit_VL53L0X.h>

// Forward declaration keeps Arduino's autogenerated function prototypes valid.
struct SensorCalibration;

struct DistanceSensor {
  Adafruit_VL53L0X vl53;
  int xshutPin = -1;
  const char* name = "sensor";
  bool occupied = false;
  bool previouslyOccupied = false;
  uint8_t detectSamples = 0;
  uint8_t clearSamples = 0;
  bool readingValid = false;
  bool triggeredThisCycle = false;
  uint16_t distanceMm = 0;
};

#endif
